name: BUILD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Dotenv Action
        uses: falti/dotenv-action@v0.2.5
        run: ${{ steps.dotenv.outputs.api_key }}

      - run: yarn
      - run: yarn build
