name: BUILD RELEASE

on:
  release:
    types: 
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: echo "github actions test" > github-actions.txt

      - name: Upload artifacts
        uses: appleboy/scp-action@master
        with:
            host: ${{ secrets.PROD_HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY_SSH }}
            source: 'github-actions.txt'
            target: '/home/ezdevs'

      - run: echo "Release published"
